[versions]
loom = "1.11.+"

minecraft = "1.21.10"
fabric-loader = "0.17.2"
parchment = "2025.07.20"
parchment_mc = "1.21.8"
fabric-api = "0.136.0+1.21.10"
sodium = "mc1.21.9-0.7.0-fabric"
modmenu = "15.0.0-beta.3"

[plugins]
loom = { id = "fabric-loom", version.ref = "loom" }

[libraries]
minecraft = { group = "mojang", name = "minecraft", version.ref = "minecraft" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }
sodium = { group = "maven.modrinth", name = "sodium", version.ref = "sodium" }
modmenu = { group = "maven.modrinth", name = "modmenu", version.ref = "modmenu" }
